### ISSUE TITLE
Minor mess in L3

### ISSUE THREAD

**Issue by Guywithoutidea** [Guywithoutidea/NZQA-Past-Papers#19]
After the addition of schedules from 2017-2019, I made a mistake: two folders for each standard now exist. One folder contains all the exams and schedules prior to 2017 and after 2019, whereas the other folder will contain schedules from 2017-2019. I do not have the time to sort this out (and I just wanted to get them on the repo before they get taken down, if NZQA get around to it) so I will just leave it as an issue for now. 

No biggie, but disorganized.

**Comment by Stxyl** [comment]
ass files named as exm files in Physics LV3?

**Comment by Stxyl** [comment]
Mess clean up addressed in this commit here
71bd5eb2f97061a2a1467d8cd0715a85cc1f926b

English LV3 Unfamiliar however don't know what's going on there as there is only ass files with no exm files.

However this issue has been addressed fixing up the structure
